# Numpy (Numerical Python)

### 1. 넘파이 설치 확인

In [1]:
import numpy as np
print(np.__version__)

2.0.1


### 2. 넘파이 배열 (ndarry) 생성과 속성 확인

In [2]:
a1 = np.array([1,2,3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
a2 = np.array((1,2,3))
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [3]:
a3 = np.array([[1,2,3], [4,5,6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [4]:
a1 = np.array([1,2,3], float) # dtype=float 가능
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)

[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [5]:
a6 = np.array([1,4,5,'8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [6]:
a6 = np.array([1,4,5,'8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [7]:
test_list = [[1,4,5,8],[1,4,5]]  # 열의 개수가 맞지 않기 때문에 error가 발생한다
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3. Indexing

In [ ]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d[0], d[1], d[2], d[-1], d[-2])

1 2 3 9 8


In [ ]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2[0][0]) # 배열명[행][열] 형태
print(d2[0,0]) # 배열명[행,열] 형태
print(d2[1,1])
print(d2[1,-1])

1
1
7
10


In [ ]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
d[3] = 100
d2[1,1] = 100
d3[1,1,1] = 1000
print(d)
print(d2)
print(d3)

[  1   2   3 100   5   6   7   8   9]
[[  1   2   3   4   5]
 [  6 100   8   9  10]]
[[[  50   50   50]
  [  50   50   50]]

 [[  30   30   30]
  [   9 1000   11]]]


In [ ]:
d2[0] = 50
d3[0] = 50
print(d2)
print(d3)

[[ 50  50  50  50  50]
 [  6 100   8   9  10]]
[[[  50   50   50]
  [  50   50   50]]

 [[  30   30   30]
  [   9 1000   11]]]


In [ ]:
d3[1,0] = 30
print(d3)

[[[  50   50   50]
  [  50   50   50]]

 [[  30   30   30]
  [   9 1000   11]]]


### 4. Slicing

In [ ]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2)
d2[:, :] = -1
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [ ]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [ ]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2[0]) # 0행만 슬라이싱
print(d2[0,:]) # 0행의 전체 열 슬라이싱
print(d2[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d2[::2, ::2]) # 2행 2열 간격으로 전채 행과 열 슬라이싱

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [ ]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [ ]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(d2)
print(d2[::2,::3])
d2[::2,::3] = 30
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]


In [ ]:
d2[:,:] = -1
print(d2)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### 5. Boolean Indexing

In [ ]:
data = np.array([4,6,7,3,2,0])
print(data > 3)
print(data[data>3])

[ True  True  True False False False]
[4 6 7]


In [ ]:
print(data > 3)
cond = [False, True, True, False, False, True]
data[cond]

[ True  True  True False False False]


array([6, 7, 0])

In [ ]:
# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 3) & (data < 6)])
# 짝수만 출력
print(data[data % 2 == 0])
# 평균보다 작은 값만 추출
print(data[data < data.mean()])

[4]
[4 6 2 0]
[3 2 0]


### 6. Fancy Indexing

In [ ]:
f = np.array([4,6,7,3,2])
indexes = np.array([1,2,0,2,2,2])
f[indexes]

array([6, 7, 4, 7, 7, 7])

In [ ]:
f2 = np.array([[1,4], [9,16]])
x = np.array([0,1,1,1,0,0])
y = np.array([0,0,0,1,1,1])
f2[x,y]

array([ 1,  9,  9, 16,  4,  4])

### 7. 넘파이 배열의 정렬

In [8]:
numbers = np.array([2,8,9,7,3,1,4,5,6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
numbers.sort()
print(numbers)

[1 2 3 4 5 6 7 8 9]


In [10]:
arr2d=np.array([[5,6,7,8],
                [4,3,2,1],
                [10,9,12,11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [ ]:
# [연습문제] 성적순으로 출력 (내림차순)
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78,95,84,98,88])

scores_sorted_index = np.argsort(scores)[::-1] # argsort(): 과값이 반환된게 아니라 원래 인덱스가 뭐였는지 나옴
print(scores_sorted_index)
print(names[scores_sorted_index]) # fancy indexing

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


### 8. 넘파이 배열의 사칙연산

In [ ]:
x = np.arange(1, 7).reshape(2,3)
print(x + x)
print(x+2)
y = np.array([10,20,30])
print(x+y)

[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
[[11 22 33]
 [14 25 36]]


### 9. 넘파이 배열의 함수

In [ ]:
d3 = np.arange(12).reshape(2, 2, 3)
# sum, max, min, mean
print(d3.sum(axis = None))
print(d3.mean(axis = None))
print(d3.max(axis = None))
print(d3.min(axis = None))

# argmax, argmin
print(d3.argmax(axis = None))
print(d3.argmin(axis = None))

66
5.5
11
0
11
0


In [ ]:
data = np.array([1,2,np.nan,4])
print(np.any(np.isnan(data)))

True


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.all(arr1==arr2))

True
